rightmenu:
  enable: false
site_footer:
  layout: []
############################### Sidebar ############################### > start
sidebar:
# 主页、分类、归档等独立页面
  # for_page: [blogger, category, tagcloud, qrcode]
  # layout: docs/post
  # for_post: [toc]
  # # 侧边栏组件库
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: https://cdn.jsdelivr.net/gh/ifeng369/blog/images/logo.jpg
      # title:
      # subtitle:
      # jinrishici:  Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: 
        # - icon: fas fa-rss
        #   url: atom.xml
        - icon: fas fa-envelope
          url: mailto:me@xaoxuu.com
        - icon: fab fa-github
          url: https://github.com/xaoxuu
        - icon: fas fa-headphones-alt
          url: https://music.163.com/#/user/home?id=63035382
    tagcloud:
      class: tagcloud
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /categories/
############################### Sidebar ############################### > end

############################### Article Layout ############################### > start
# 文章布局
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/ifeng369/blog/icon/pin.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show author
    author: true # true, false
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category,tags, date,counter]
    # ----------------
    # 文章页脚组件
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fas fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 相关文章，需要安装插件 (for layout: post)
      # npm i hexo-related-popular-posts
      related_posts:
        enable: false
        title: 相关文章
        icon: fas fa-bookmark
        max_count: 5
        # 设为空则不使用文章头图
        placeholder_img: data:image/png;base64,666
      # ----------------
      # 版权声明组件 (for layout: post)
      copyright:
        enable: false
        permalink: #'本文永久链接是：'
        content:
          #- '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
          #- permalink
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [updated, tags,wordcount]
    # meta library
    meta_library:
      # 默认文章作者（可在 front-matter 中覆盖）
      author:
        avatar: https://cdn.jsdelivr.net/gh/ifeng369/blog/images/logo.jpg
        name: ifeng
        # url: https://volantis.weijiajin.com
      # 文章创建日期
      date:
        icon: fas fa-calendar-alt
        title: '发布于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fas fa-edit
        title: '更新于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fas fa-folder-open
      # 文章浏览计数
      counter:
        icon: fas fa-eye
        unit: '次浏览'
      # 文章评论数量：只支持 valine
      valinecount:
        icon: fas fa-comment-dots
        desc: '' # 条评论
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fas fa-keyboard
        icon_duration: fas fa-hourglass-half
      # 文章标签
      tags:
        icon: fas fa-hashtag
      # 分享
      # share:
      #   - id: qq
      #     img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
      #   - id: qzone
      #     img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
      #   - id: weibo
      #     img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
      #   - id: # qrcode # 当id为qrcode时需要安装插件  npm i hexo-helper-qrcode
      #     img: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/wechat.png
      #   - id: # telegram
      #     img: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png
############################### Article Layout ############################### > end



############################### Cover ############################### > start
cover:
  height_scheme: half # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: true # can be written in front-matter 'cover: true'
  background: https://cdn.jsdelivr.net/gh/ifeng369/blog/images/033.jpg
  title: 'ifeng’s blog'
  subtitle: "「Stay Hungry.Stay Foolish.」"
  search:  # search bar placeholder
  features:
    - name: 博客
      url: /
    - name: 归档
      url: archives/
    - name: 分类
      url: categories/
    - name: 标签
      url: tags/
    - name: 关于
      url: about/
############################### Cover ############################### > end


############################### Navigation Bar ############################### > start
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: #https://cdn.jsdelivr.net/gh/ifeng369/blog/images/logo.jpg
    icon: 
    title: weijiajin
  menu:
    - name: 博客
      icon: fas fa-code
      url: /
    #- name: 分类
    #  icon: fas fa-folder-open
    #  url: categories/
    #- name: 标签
    #  icon: fas fa-tags
    #  url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    #- name: 友链
    #  icon: fas fa-link
    #  url: friends/
   # - name: 评论
    #  icon: fas fa-comment-dots
     # url: https://feelheart.leanapp.cn/
    #- name: 关于
     # icon: fas fa-info-circle
     # url: about/
  search:    # Search bar placeholder
############################### Navigation Bar ############################### > end

############################### Search ############################### > start
# To use hexo search, you need to install the following plugins:
# npm i hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo
############################### Search ############################### > end

############################### Color Scheme ############################### > start
color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: '#44D7B6'
    # 链接色
    link: '#2196f3'
    # 按钮色
    button: '#44D7B6'
    # 鼠标放到交互元素上时的色
    hover: '#ff5722'
    # 主题色块内部的文字颜色
    inner: '#fff'
    # 选中区域文字的背景颜色
    selection: 'alpha(#2196f3, 0.2)'
  # ------------
  # 亮色主题（默认）
  light:
    # 网站背景色
    site_bg: '#66859F'
    # 网站背景上的文字
    site_inner: '#fff'
    # 网站页脚文字
    site_footer: '#fff'

    # 卡片背景色
    card: '#fff'
    # 卡片上的普通文字
    text: '#444'

    # 区块和代码块背景色
    block: '#f6f6f6'
    # 代码块高亮时的背景色
    codeblock: '#FFF7EA'
    # 行内代码颜色
    inlinecode: '#c74f00'

    # 文章部分
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#333'
    h4: '#444'
    h5: '#555'
    h6: '#666'
    p: '#444'

    # 列表文字
    list: '#666'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #000, 80)'
    # 辅助性文字
    meta: '#888'
  # ------------
  # 暗色主题
  dark:
    # 网站背景色
    site_bg: '#222'
    # 网站背景上的文字
    site_inner: '#eee'
    # 网站页脚文字
    site_footer: '#aaa'
    # 卡片背景色
    card: '#333'
    # 卡片上的普通文字
    text: '#eee'

    # 区块和代码块背景色
    block: '#3a3a3a'
    # 代码块高亮时的背景色
    codeblock: '#343a3c'
    # 行内代码颜色
    inlinecode: '#D56D28'

    # 文章部分
    h1: '#eee'
    h2: '#eee'
    h3: '#ddd'
    h4: '#ddd'
    h5: '#ddd'
    h6: '#ddd'
    p: '#bbb'

    # 列表文字
    list: '#aaa'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #fff, 80)'
    # 辅助性文字
    meta: '#888'
    # 夜间图片亮度
    brightness: 70%
############################### Color Scheme ############################### > end
############################### Custom css ############################### > start
custom_css:
  toc_smooth: true # TOC 目录平滑滚动效果
  cursor:
    enable: false
  font_smoothing: true # font-smoothing for webkit
  max_width: 1080px # Sum of body width and sidebar width (This limit will be exceeded when the device width is greater than 2000px, reaching 75% of the total width)
  scrollbar:
    size: 4px
    border: 2px
  navbar:
    height: 64px
    width: auto # auto, max
    effect: [shadow, floatable,blur] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow, floatable, blur] # [shadow, floatable, blur]
  body:
    effect: [shadow, floatable, blur] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      copy_btn: true
      grayscale: false # Enable grayscale effect
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
  gap:
    h2: 48px # Spacing above H2 (only px unit)
    h3: 24px # Spacing above H3 (only px unit)
    h4: 16px # Spacing above H4 (only px unit)
    p: 1em # Paragraph spacing between paragraphs
    line_height: 1.6 # normal, 1.5, 1.75, 2 ...
  border_radius:
    card: 8px
    codeblock: 4px
    searchbar: 8px
    button: 4px
  fontsize:
    root: 16px
    h1: 1.5rem # 不推荐用在文章中
    h2: 1.5rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .78125rem
  fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/ifeng369/blog/font/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'UbuntuMono, "Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/ifeng369/blog/font/UbuntuMono-Regular.ttf
      weight: normal
      style: normal
    codefont:
      fontfamily: 'Menlo, UbuntuMono, Monaco'
      name: 'Monaco'
      url: https://cdn.jsdelivr.net/gh/ifeng369/blog/font/Monaco.ttf
      weight: normal
      style: normal
############################### Custom css ############################### > end
plugins:
  parallax:
    enable: true
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 30000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/001.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/002.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/003.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/004.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/005.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/006.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/007.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/008.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/009.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/010.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/011.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/012.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/013.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/014.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/015.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/016.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/017.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/018.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/019.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/020.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/021.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/022.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/023.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/024.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/025.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/026.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/027.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/028.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/029.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/030.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/031.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/032.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/033.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/034.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/035.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/036.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/037.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/038.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/039.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/040.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/041.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/042.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/043.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/044.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/045.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/046.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/047.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/048.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/049.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/050.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/051.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/052.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/053.jpg
      # - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/054.jpg
      - https://cdn.jsdelivr.net/gh/ifeng369/blog/images/055.jpg